### ISSUE TITLE
LIBICA Version not shown

### ISSUE THREAD

**Issue by alexiswl** [umccr/icav2-cli-plugins#199]
```
$ icav2 --version
icav2-cli-plugins-version: v2.14.0--patch-81b9940
libica module version: __LIBICA_VERSION__
icav2 version 2.16.0
```

**Comment by victorskl** [comment]
Just sharing note --

You might already be doing this...

```
from importlib.metadata import version
...
...
print(f"libica-{version('libica')}")
```

https://github.com/umccr-illumina/libica/blob/d3b41b644236c6d1a9d69ab8714f6ec098940c48/examples/create_cwl_pipeline.py#L20

https://github.com/umccr-illumina/libica/blob/d3b41b644236c6d1a9d69ab8714f6ec098940c48/examples/create_cwl_pipeline.py#L39
